name: build

on:
  push:
    branches: [ "feature/build_deploy" ]
  pull_request:
    branches: [ "feature/build_deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: show directory
      run: |
        cd ..
        ls -A
    - name: Restore dependencies
      run: dotnet restore ../../src/Worms.API/Worms.API.sln
    - name: Build
      run: dotnet build ../../src/Worms.API --no-restore
    - name: Test
      run: dotnet test ../../src/Worms.API --no-build --verbosity normal