name: deploy

env:
  SOLUTION_PATH: '../worms-tg-app/src/Worms.API'
  AZURE_WEBAPP_NAME: 'ass-worms-dev-001'
  AZURE_WEBAPP_PACKAGE_PATH: '.' 

on:
  push:
    branches: [ "feature/build_deploy" ]
  pull_request:
    branches: [ "feature/build_deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}/Worms.API.sln
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore
    - name: Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}